# Generated by Django 4.2.14 on 2024-07-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="slug",
        ),
    ]
