# Generated by Django 4.2.14 on 2024-07-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_remove_about_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
